# Generated by Django 4.1.3 on 2022-11-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_picture',
            field=models.ImageField(default='react.png', upload_to='post_pictures'),
        ),
    ]
