# Generated by Django 4.1.3 on 2022-11-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='blank-profile-picture.jpg', upload_to='profile_pictures'),
        ),
    ]
